apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcabank-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mcabank-frontend
  template:
    metadata:
      labels:
        app: mcabank-frontend
    spec:
      containers:
        - name: mcabank-frontend
          image: rasteiro11/mcabank-frontend:20250914164556
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mcabank-frontend
spec:
  selector:
    app: mcabank-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mcabank-frontend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mcabank-frontend
            port:
              number: 80
